CREATE TABLE `usuarios` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`nickName` VARCHAR(50) NOT NULL UNIQUE,
	`descripcion` VARCHAR(100) NOT NULL DEFAULT 'soy un marinero en busca de tesoros',
	`avatarId` INTEGER NOT NULL DEFAULT 1,
	`correo` VARCHAR(150) NOT NULL UNIQUE,
	`contraseña` VARCHAR(15) NOT NULL,
	`monedas` BIGINT NOT NULL DEFAULT 200,
	PRIMARY KEY(`id`)
);


CREATE TABLE `juegos` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`nombre` VARCHAR(30) NOT NULL UNIQUE,
	`descripcion` TEXT(65535) NOT NULL,
	`imagen` TEXT(65535) NOT NULL UNIQUE,
	`maximoNiveles` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `avatares` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`nombre` VARCHAR(50) NOT NULL UNIQUE,
	`imagen` TEXT(65535) NOT NULL UNIQUE,
	`valor` BIGINT NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `niveles` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`nombre` VARCHAR(50) NOT NULL,
	`numero` BIGINT NOT NULL,
	`tiempo` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `historialNiveles` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`usuarioId` INTEGER NOT NULL,
	`juegoId` INTEGER NOT NULL,
	`nivelId` INTEGER NOT NULL,
	`puntos` BIGINT NOT NULL,
	`tiempo` TIME NOT NULL,
	`monedas` BIGINT NOT NULL,
	`estadoNivel` BOOLEAN NOT NULL,
	fechaInicio DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE `avatarTienda` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`usuarioId` INTEGER NOT NULL,
	`avatarId` INTEGER NOT NULL,
	`fechaCompra` TIMESTAMP NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `sala` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`creadorId` INTEGER NOT NULL,
	`nombre` VARCHAR(50) NOT NULL,
	`codigo` BIGINT NOT NULL,
	`capacidad` INTEGER NOT NULL,
	`dificultad` VARCHAR(20) NOT NULL,
	`rondas` INTEGER NOT NULL,
	`rondaActual` INTEGER NOT NULL,
	`estado` VARCHAR(50) NOT NULL DEFAULT 'abierta',
	`fechaCreacion` TIMESTAMP NOT NULL,
	`estadoFinalizado` BOOLEAN NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `participantes` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`salaId` INTEGER NOT NULL,
	`usuarioId` INTEGER NOT NULL,
	`fechaIngreso` INTEGER,
	PRIMARY KEY(`id`)
);


CREATE TABLE `palabra` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`palabra` VARCHAR(20) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `palabraNivel` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`palabraId` INTEGER NOT NULL,
	`nivelId` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `pista` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`palabraId` INTEGER NOT NULL,
	`pista` TEXT(65535) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `imagenNivel` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`imagenId` INTEGER NOT NULL,
	`nivelId` INTEGER NOT NULL,
	`area` INTEGER NOT NULL,
	`movimientosMin` INTEGER NOT NULL,
	PRIMARY KEY (`id`)
);


CREATE TABLE `imagen` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`nombre` VARCHAR(100) NOT NULL,
	`url` TEXT(65535) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE rondas (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	salaId INTEGER NOT NULL,
	numeroRondas INTEGER NOT NULL,
	fechaInicio DATETIME NOT NULL,
	fechaFin DATETIME,
	estadoFinalizado BOOLEAN NOT NULL,
	PRIMARY KEY(id)
);


CREATE TABLE historialRonda (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	rondaId INTEGER NOT NULL,
	participanteId INTEGER NOT NULL,
	tiempo TIME NOT NULL,
	puntos BIGINT NOT NULL,
	podio INTEGER NOT NULL,
	fechaInicio DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
);

CREATE TABLE historialSala (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	salaId INTEGER NOT NULL,
	participanteId INTEGER NOT NULL,
	tiempoPromedio TIME NOT NULL,
	puntosTotal BIGINT NOT NULL,
	podioFinal INTEGER NOT NULL,
	fechaInicio DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
);



ALTER TABLE `sala`
ADD FOREIGN KEY(`creadorId`) REFERENCES `usuarios`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `participantes`
ADD FOREIGN KEY(`salaId`) REFERENCES `sala`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `participantes`
ADD FOREIGN KEY(`usuarioId`) REFERENCES `usuarios`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `avatarTienda`
ADD FOREIGN KEY(`usuarioId`) REFERENCES `usuarios`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `usuarios`
ADD FOREIGN KEY(`avatarId`) REFERENCES `avatares`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `avatarTienda`
ADD FOREIGN KEY(`avatarId`) REFERENCES `avatares`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `historialNiveles`
ADD FOREIGN KEY(`usuarioId`) REFERENCES `usuarios`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `historialNiveles`
ADD FOREIGN KEY(`juegoId`) REFERENCES `juegos`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `historialNiveles`
ADD FOREIGN KEY(`nivelId`) REFERENCES `niveles`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `imagenNivel`
ADD FOREIGN KEY(`nivelId`) REFERENCES `niveles`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `imagenNivel`
ADD FOREIGN KEY(`imagenId`) REFERENCES `imagen`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `palabraNivel`
ADD FOREIGN KEY(`palabraId`) REFERENCES `palabra`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `palabraNivel`
ADD FOREIGN KEY(`nivelId`) REFERENCES `niveles`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `pista`
ADD FOREIGN KEY(`palabraId`) REFERENCES `palabra`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `rondas`
ADD FOREIGN KEY(`salaId`) REFERENCES `sala`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `historialSala`
ADD FOREIGN KEY(`salaId`) REFERENCES `sala`(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `historialSala`
ADD FOREIGN KEY(`participanteId`) REFERENCES `participantes`(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `historialRonda`
ADD FOREIGN KEY(`rondaId`) REFERENCES `rondas`(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `historialRonda`
ADD FOREIGN KEY(`participanteId`) REFERENCES `participantes`(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;